package com.seva60plus.hum.activity;

import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.webkit.WebView;
import android.widget.Button;

import com.seva60plus.hum.R;




public class Privacy extends Activity {
	
	Button close;
 
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.privacy);

        
      /*  TextView text = (TextView)findViewById(R.id.privacy);
        TextView text2 = (TextView)findViewById(R.id.privacy_title);
        */
        WebView web = (WebView)findViewById(R.id.privacy_web);
        web.loadUrl("file:///android_asset/Hum_Privacy_Policy.html");
        
//        /*  text2.setText(Html.fromHtml("<u><strong>PRIVACY POLICY OF SEVA60PLUS HUM</u></strong><br/>"));
//       text.setText(Html.fromHtml("<strong>1. GENERAL</strong><br/><br/>"+"a)   This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signature."+"<br/><br/>"
//        +"b)  This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and terms of use for access or usage of the application <strong>â€˜SEVA60PLUS HUMâ€™</strong> (â€œ<strong>Application</strong>â€�)."+"<br/><br/>"
//        +"c) The Application is owned and operated by <strong>Seva60plus Mobility LLP</strong> (â€œ<strong>Company</strong>â€�), a limited liability partnership firm, registered under the provisions of the Limited Liability Partnership Act, 2008, and having its registered office at <strong> DG2/107A, Vikas Puri, New Delhi-110018, India, </strong> where such expression shall, unless repugnant to the context thereof, be deemed to include its respective representatives, administrators, employees, directors, officers, agents and their successors and assigns."+"<br/><br/>"
//        +"d) For the purpose of this Privacy Policy (â€œ<strong>Policy</strong>â€�), wherever the context so requires:<br/>" +
//        "i) The term <strong> â€˜the Userâ€™ & â€˜Userâ€™ </strong> shall mean any legal person or entity accessing or using the Service (defined hereinbelow) provided on the Application, who is competent to enter into binding contracts, as per the provisions of the Indian Contract Act, 1872; and <br/> " +
//        "ii) The terms <strong> â€˜Partyâ€™ & â€˜Partiesâ€™ </strong> shall respectively be used to refer to the User and the Company individually and collectively, as the context so requires;"+"<br/><br/>"
//        +""
//        ));*/
        
       
        
      //  Typeface font = Typeface.createFromAsset(getAssets(), "openSansRegular.ttf");
      //  text.setTypeface(font);
        
        close=(Button)findViewById(R.id.close);
      //  close.setTypeface(font);
        close.setOnClickListener(new View.OnClickListener() {
	        @Override
	        public void onClick(View view) {
	            // Take action.
	        	finish();
	        	
	        }
	    });
        
        
        
        
}
}